### ISSUE TITLE
Basic Authentication

### ISSUE THREAD

**Issue by aulianapip** [sap-labs-france/ev-simulator#18]
Hi, I want to ask if it supports this ev-simulator using Basic Authentication Profile ?
as stated in the document OCPP 1.6 security whitepaper edition 2.

**Comment by jerome-benoit** [comment]
Yes, as supported by the ws dependency, but with some drawbacks: the same user/password will be used by all charging stations templates using the same connection URI. 

The fork I maintain https://github.com/jerome-benoit/ev-simulator have also user/pass support in templates amongst added features.

**Comment by LucasBrazi06** [comment]
Closed for inactivity reason.
