### ISSUE TITLE
Duplicate process

### ISSUE THREAD

**Issue by nazlikrmn** [sap-labs-france/ev-simulator#195]
![image](https://user-images.githubusercontent.com/26343034/161266213-db19ee39-b0d1-4095-9477-7145bdc48b8a.png)

could you explain the reason of this code. Why should we try 2 times. 

here I only see 2 elements with the same name with different case.

src/charging-station/ChargingStation.ts

**Comment by LucasBrazi06** [comment]
Yes, the case is sensitive and in some charging stations the standard param is rejected.
