### ISSUE TITLE
The templates listed in ev-simulator are not able to be used with latest ev-server 

### ISSUE THREAD

**Issue by jijoy** [sap-labs-france/ev-simulator#230]
I have taken latest code from master-qa branch from ev-server and master from ev-simulator .  However the charging stations are listed as manual configuration.  The templates available in the ev-simulator project are not compatable with latest ev-server code. 

However I am unable to find any reference of this in the documentation.

**Comment by jerome-benoit** [comment]
Repository moved to https://github.com/SAP/e-mobility-charging-stations-simulator.
