### ISSUE TITLE
 issu when install ev simulator

### ISSUE THREAD

**Issue by zhangsdf** [sap-labs-france/ev-simulator#232]
it said can not find “ \dist\start.js'|

<img width="599" alt="22" src="https://user-images.githubusercontent.com/128835259/227591918-77b59cca-ec9f-4754-acf2-6b2dfd5d1a3c.png">

**Comment by jerome-benoit** [comment]
Repository moved to https://github.com/SAP/e-mobility-charging-stations-simulator.
