### ISSUE TITLE
Getting unexpected token ? error while trying to run the simulator

### ISSUE THREAD

**Issue by Pulse-akhil** [sap-labs-france/ev-simulator#47]
While trying to run the simulator I get the following error. The config.json and authorization-tags.json file looks intact to me. From the logs below are you able to see what may be going wrong here?

src/start.ts, src/charging-station/ChargingStationWorker.ts → dist...
created dist in 15.6s

> ev-simulator@1.1.6 start /root/ev-simulator
> cross-env NODE_ENV=production node -r source-map-support/register dist/start.js

/root/ev-simulator/dist/charging-station/Bootstrap.js:1
"use strict";var e=require("../types/Worker.js"),t=require("../utils/Configuration.js"),r=require("../performance/storage/StorageFactory.js"),o=require("../utils/Utils.js"),a=require("../worker/WorkerFactory.js"),n=require("chalk"),i=require("worker_threads"),s=require("path"),l=require("../package.json.js");function g(e){return e&&"object"==typeof e&&"default"in e?e:{default:e}}var c=g(n),m=g(s);class u{constructor(){this.version=l.version,this.started=!1,this.workerScript=m.default.join(m.default.resolve(__dirname,"../"),"charging-station","ChargingStationWorker.js"),this.initWorkerImplementation(),u.storage=r.StorageFactory.getStorage(t.getPerformanceStorage().type,t.getPerformanceStorage().URI,this.logPrefix()),t.setConfigurationChangeCallback((async()=>u.getInstance().restart()))}static getInstance(){return u.instance||(u.instance=new u),u.instance}async start(){if(i.isMainThread&&!this.started)try{if(u.numberOfChargingStations=0,await u.storage.o

SyntaxError: Unexpected token ?
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/root/ev-simulator/dist/start.js:1:20)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ev-simulator@1.1.6 start: `cross-env NODE_ENV=production node -r source-map-support/register dist/start.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ev-simulator@1.1.6 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-09-25T13_49_27_017Z-debug.log

**Comment by Pulse-akhil** [comment]
Looks like the docker build works with the same config file. So there is something else is going on

**Comment by LucasBrazi06** [comment]
Thanks for reporting the issue, I will check.

**Comment by LucasBrazi06** [comment]
I just fixed a build error, upgraded to node 16 and npm 8.
Could you please remove your node modules and give it another try?
Let me know.
